KEEP_ONLY = {
    'py_analyzer',
    'image_io',
    'easy_lib',
    # 'sandbox',
    # 'sandbox_core',
    # 'sandbox_creature',
    # 'sandbox_gui',
    # 'sandbox_lib',
    # 'sandbox_procedural',
}

STD_LIB = {
    'typing',
    'unittest',
    'time',
    'threading',
    'tempfile',
    'sys',
    'uuid',
    'shutil',
    'pickle',
    'random',
    'pathlib',
    'os',
    'traceback',
    'math',
    'logging',
    'enum',
    'functools',
    'itertools',
    'inspect',
    'json',
    'operator',
    'array',
    'abc',
    'dataclasses',
    'datetime',
}
